// Fake API
export const REQUEST_ALL_PRODUCTS = 'product/REQUEST_ALL_PRODUCTS';
export const REQUEST_ALL_PRODUCTS_ERROR = 'product/REQUEST_ALL_PRODUCTS_ERROR';
export const REQUEST_ALL_PRODUCTS_SUCCESS = 'product/REQUEST_ALL_PRODUCTS_SUCCESS';